---
kind: ImageStream
apiVersion: v1
metadata:
  name: wildfly-runtime-170-centos7
spec:
  tags:
  - name: latest
    annotations:
      description: wildfly-runtime image stream
      iconClass: icon-jboss
      tags: java,widlfly
      version: 'latest'
    from:
      kind: DockerImage
      name: "quay.io/jfdenise/wildfly-runtime-170-centos7:latest"