kind: Service
apiVersion: v1
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
spec:
  selector:
    app: keycloak-server
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30079
      name: http

