---
kind: ImageStream
apiVersion: v1
metadata:
  name: wildfly-runtime
spec:
  tags:
  - name: latest
    annotations:
      description: wildfly-runtime image stream
      iconClass: icon-wildfly
      tags: java,widlfly
      version: 'latest'
    from:
      kind: DockerImage
      name: "quay.io/wildfly/wildfly-runtime:latest"
  - name: "19.0"
    annotations:
      description: wildfly-runtime image stream
      iconClass: icon-wildfly
      tags: java,widlfly
      version: '19.0'
    from:
      kind: DockerImage
      name: "quay.io/wildfly/wildfly-runtime-centos7:19.0"
