kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jms-journal
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  

