name: Wildfly s2i Image with custom wildfly-cekit-module
on:
  repository_dispatch:
    types: [tag-released-images]
env:
  LANG: en_US.UTF-8
  QUAY_REPO: ${{ secrets.QUAY_REPO }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
jobs:
  wfci:
    name: Wildfly-s2i tag released images
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.client_payload.wf-s2i-ref }}
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check quay.io configuration
        if: env.QUAY_USERNAME == '' || env.QUAY_REPO == ''
        run: |
          echo "quay.io configuration is incomplete, can't push to quay.io. To push built images to quay.io, please ensure the secrets QUAY_REPO, QUAY_USERNAME and QUAY_PASSWORD are created in the project."
          exit 1
      - name: Tag images
        run: |
          docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
          if [ -f ./perform-release.sh ]; then
            echo "Tagging images from staging repositories. Executing:"
            cat ./perform-release.sh
            sh ./perform-release.sh
          else
            echo "ERROR perform-release.sh file not found. You must first run tools/github-prepare-release.sh"
          fi